# Generated by Django 5.1.6 on 2025-03-05 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_meal', '0002_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllergicRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(max_length=255)),
                ('health_benefits', models.TextField()),
                ('cooking_procedure', models.TextField()),
                ('how_to_serve', models.TextField()),
                ('meal_time', models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner')], max_length=10)),
                ('meal_image', models.ImageField(blank=True, null=True, upload_to='meal_images/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DiabeticRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(max_length=255)),
                ('health_benefits', models.TextField()),
                ('cooking_procedure', models.TextField()),
                ('how_to_serve', models.TextField()),
                ('meal_time', models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner')], max_length=10)),
                ('meal_image', models.ImageField(blank=True, null=True, upload_to='meal_images/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NormalRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(max_length=255)),
                ('health_benefits', models.TextField()),
                ('cooking_procedure', models.TextField()),
                ('how_to_serve', models.TextField()),
                ('meal_time', models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner')], max_length=10)),
                ('meal_image', models.ImageField(blank=True, null=True, upload_to='meal_images/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VegetarianRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(max_length=255)),
                ('health_benefits', models.TextField()),
                ('cooking_procedure', models.TextField()),
                ('how_to_serve', models.TextField()),
                ('meal_time', models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner')], max_length=10)),
                ('meal_image', models.ImageField(blank=True, null=True, upload_to='meal_images/')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
