# Generated by Django 5.1.6 on 2025-03-16 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_meal', '0004_allergicdesserts_allergicdrinks_allergicfruits_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='bio',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
