# Generated by Django 5.1.6 on 2025-03-17 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_meal', '0005_userprofile_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='health_goals',
            field=models.CharField(choices=[('weight_increase', 'Weight_Increase'), ('weight_loss', 'Weight_Loss'), ('weight_retantion', 'Weight_Retantion')], default='normal', max_length=50),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='weight',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
