# Generated by Django 5.1.6 on 2025-03-20 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_meal', '0006_userprofile_health_goals_userprofile_weight'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dessert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='dessert_images/')),
                ('category', models.CharField(choices=[('allergic', 'Allergic'), ('diabetic', 'Diabetic'), ('vegetarian', 'Vegetarian'), ('normal', 'No Restrictions')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Drink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='drink_images/')),
                ('category', models.CharField(choices=[('allergic', 'Allergic'), ('diabetic', 'Diabetic'), ('vegetarian', 'Vegetarian'), ('normal', 'No Restrictions')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Fruit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='fruit_images/')),
                ('category', models.CharField(choices=[('allergic', 'Allergic'), ('diabetic', 'Diabetic'), ('vegetarian', 'Vegetarian'), ('normal', 'No Restrictions')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Snack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='snack_images/')),
                ('category', models.CharField(choices=[('allergic', 'Allergic'), ('diabetic', 'Diabetic'), ('vegetarian', 'Vegetarian'), ('normal', 'No Restrictions')], max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='AllergicDesserts',
        ),
        migrations.DeleteModel(
            name='AllergicDrinks',
        ),
        migrations.DeleteModel(
            name='AllergicFruits',
        ),
        migrations.DeleteModel(
            name='AllergicSnacks',
        ),
        migrations.DeleteModel(
            name='DiabeticDesserts',
        ),
        migrations.DeleteModel(
            name='DiabeticDrinks',
        ),
        migrations.DeleteModel(
            name='DiabeticFruits',
        ),
        migrations.DeleteModel(
            name='DiabeticSnacks',
        ),
        migrations.DeleteModel(
            name='NormalDesserts',
        ),
        migrations.DeleteModel(
            name='NormalDrinks',
        ),
        migrations.DeleteModel(
            name='NormalFruits',
        ),
        migrations.DeleteModel(
            name='NormalSnacks',
        ),
        migrations.DeleteModel(
            name='VegeterianDesserts',
        ),
        migrations.DeleteModel(
            name='VegeterianDrinks',
        ),
        migrations.DeleteModel(
            name='VegeterianFruits',
        ),
        migrations.DeleteModel(
            name='VegeterianSnacks',
        ),
    ]
