# Generated by Django 5.1.6 on 2025-03-23 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_meal', '0007_dessert_drink_fruit_snack_delete_allergicdesserts_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeightManagementFood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='weight_foods/')),
                ('category', models.CharField(choices=[('gain', 'Weight Gain'), ('loss', 'Weight Loss'), ('maintain', 'Weight Maintenance')], max_length=10)),
            ],
        ),
    ]
