# Generated by Django 5.1.6 on 2025-03-24 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_meal', '0009_alter_weightmanagementfood_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthHabits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='health_habits/')),
            ],
        ),
    ]
